repos:
    - repo: https://github.com/antonbabenko/pre-commit-terraform
      rev: v1.99.0
      hooks:
      - id: terraform_fmt
      # - id: terraform_validate
      #   args:
      #     - --hook-config=--retry-once-with-cleanup=true
      - id: terraform_providers_lock
        args:
          - --hook-config=--mode=only-check-is-current-lockfile-cross-platform
          - --args=-platform=windows_amd64
          - --args=-platform=darwin_amd64
          - --args=-platform=darwin_arm64
      - id: terraform_tflint
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md        
          - --hook-config=--add-to-existing-file=true   
          - --hook-config=--create-file-if-not-exist=true